version: '3'

services: 
  django_app:
    build: .
    volumes:
      - ./goksoyakademi/static:/static/
    ports: 
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - ./goksoyakademi/static:/static/
    ports: 
      - "80:80"
    depends_on:
      - django_app

volumes:
  static_vol:



