# Generated by Django 4.2.3 on 2023-09-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('thumbnail', models.ImageField(upload_to='image')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
        ),
    ]
