Courses=[
    { 
        '_id' : '1',
        'baslik' : 'Fransızca Kursu', 
        'dil' : 'fransizca',
        'author' : 'Kemal Okan Dikkulak',
        'videosIds' : ['233','234', '235'],
        'date' : '12-12-2023',
        'quizIds' : ['233'],
        'students' : '15',
        'price' : '350',
        'description' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint voluptatibus quo pariatur quas quia numquam blanditiis, quisquam magni, ipsum aut voluptates, assumenda mollitia quidem necessitatibus.',
    },
    { 
        '_id' : '2',
        'baslik' : 'İngilizce Dilbilgisi', 
        'dil' : 'ingilizce',
        'author' : 'Ali Haydar Göksoy',
        'videosIds' : ['236','237', '238'],
        'date' : '12-12-2023',
        'quizIds' : ['234'],
        'students' : '15',
        'price' : '450',
        'description' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint voluptatibus quo pariatur quas quia numquam blanditiis, quisquam magni, ipsum aut voluptates, assumenda mollitia quidem necessitatibus.',
    },
    { 
        '_id' : '3',
        'baslik' : 'İngilizce A1.1 - A1.3', 
        'dil' : 'ingilizce',
        'author' : 'Ali Haydar Göksoy',
        'videosIds' : ['133','134', '135'],
        'date' : '12-12-2023',
        'quizIds' : ['235'],
        'students' : '15',
        'price' : '150',
        'description' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint voluptatibus quo pariatur quas quia numquam blanditiis, quisquam magni, ipsum aut voluptates, assumenda mollitia quidem necessitatibus.',
    },
    { 
        '_id' : '4',
        'baslik' : 'Fransız Dilbilgisi', 
        'dil' : 'fransizca',
        'author' : 'Kemal Okan Dikkulak',
        'videosIds' : ['122','124', '125'],
        'date' : '12-12-2023',
        'quizIds' : ['236'],
        'students' : '15',
        'price' : '250',
        'description' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint voluptatibus quo pariatur quas quia numquam blanditiis, quisquam magni, ipsum aut voluptates, assumenda mollitia quidem necessitatibus.',
    },
]